services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - db  # Backend, veritabanı başlamadan başlamasın

  # MONGODB SERVİSİ
  db:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    volumes:
      - mongo_data:/data/db 

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://13.49.67.193:5000/api
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: